In [1]:
import numpy as np #alias -> np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
# dimensions and shape of an array
arr.ndim

1

In [4]:
arr =np.array(34)
arr.ndim

0

In [5]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [6]:
range = np.arange(1,10, 2) #start, stop, step

In [7]:
range

array([1, 3, 5, 7, 9])

In [8]:
arr = np.linspace(0,1,10) #start, stop, number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
arr = np.logspace(1, 3, 2) #logarithmic scale array -> 10^1 -> 10^3 ... 3 points
arr

array([  10., 1000.])

In [10]:
# np.logspace(start, ending -> powers, 3 -> number of values)

In [11]:
# np.zeros -> array full of zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [12]:
arr = np.zeros([2,3]) #array full of zeros
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr = np.ones([4,2]) #array full of ones.
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
rr = np.full(10, 2) #-> create an array full of any value
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
arr = np.full([2,4], 7.1) #[row, column], default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [16]:
arr = np.empty([2,3]) #Uninitialized array -> create an array without setting any values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr = np.random.rand(10)
arr #-> random floats(0 to 1)

array([0.32194531, 0.35680216, 0.72762458, 0.10799897, 0.20063494,
       0.44329827, 0.20673384, 0.01253537, 0.01966962, 0.93213866])

In [18]:
arr = np.random.rand(2,3)
arr

array([[0.45614406, 0.20297702, 0.29925183],
       [0.60022335, 0.67557745, 0.90301697]])

In [19]:
arr = np.random.randn(2,3)
arr #-> random floats from standard normal distribution

array([[ 0.82051514, -1.10686891, -1.07308204],
       [-2.19612288,  1.09004026, -0.27329672]])

In [20]:
arr = np.random.randint(10, 100) #->start, stop, dimension/number of values
arr#-> random integers

77

In [21]:
arr = np.random.randint(10, 100, size = (2,3)) #->start, stop, dimension/number of values
arr

array([[58, 20, 90],
       [68, 66, 16]], dtype=int32)

In [22]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [23]:
arr.dtype

dtype('float64')

In [24]:
lst = ["string", 1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [25]:
arr = np.array(["1",2,3.1,4,5])
arr

array(['1', '2', '3.1', '4', '5'], dtype='<U32')

In [26]:
arr.dtype

dtype('<U32')

In [27]:
arr = np.array([1.1, 2.6 , 3 , 4], dtype = np.int64)

In [28]:
arr.dtype

dtype('int64')

In [29]:
arr

array([1, 2, 3, 4])

In [30]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [31]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [32]:
new_arr.dtype

dtype('float64')

In [33]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

In [35]:
# Type Casting errors:

arr = np.array(["1", "2", "hello"])
arr_fixed = np.where(np.char.isnumeric(arr), arr, "0").astype(np.int64)
print(arr_fixed)



[1 2 0]


In [36]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr.ndim

2

In [39]:
arr.shape

(2, 3)

In [40]:
arr.size

6

In [41]:
arr.itemsize

8

In [42]:
# Reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [43]:
reshape2 = reshaped.reshape(3,2)

In [44]:
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
#ravel -> convert 1D array
ravel = reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [46]:
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [47]:
#flatten -> to 1D array
# -> returns a copy of the array

flat = reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [48]:
flat[0] = 1

In [49]:
flat

array([1, 2, 3, 4, 5, 6])

In [50]:
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [53]:
#addition:

print(a+b)

[5 7 9]


In [54]:
# subtraction
print(b-a)

[3 3 3]


In [55]:
#division:
print(a/b)

[0.25 0.4  0.5 ]


In [56]:
# integer division
print(b//a)

[4 2 2]


In [57]:
#multiplication
print(a*b)

[ 4 10 18]


In [58]:
#modulus -> remainder
print(b%a)

[0 1 0]


In [59]:
# exponent -> power
print(a**2)

[1 4 9]


In [60]:
#universalfunction

arr = np.array([1,4,9,16])

In [61]:
# Square root -> np.sqrt()

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [62]:
# exponentioal -> np.exp -> e^x -> x is any integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [63]:
#sine function -> np.sin

angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [64]:
#indexing and slicing

a = [1,2,3,4,5]

In [65]:
a[-1:-4: -1]

[5, 4, 3]

In [66]:
a[: :2]

[1, 3, 5]

In [67]:
arr = np.array([10,20,30,40,50])
# indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

In [68]:
# Negative Indexing
print(arr[-1])

50


In [69]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [70]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [71]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [72]:
#np.take -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [73]:
# Iterating with nditer()

In [74]:
arr= np.array([[1,2], [3,4]])

In [75]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

In [76]:
# ndenumerate() -> both index + value

for ind, x in np.ndenumerate(arr):
  print(ind, x)



(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [77]:
# Views vs Copies

arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [78]:
view[0] = 200

In [79]:
view


array([200,   3])

In [80]:
arr


array([  1, 200,   3,   4,   5])

In [81]:

arr = np.array([[1,2], [3,4]])
arr


array([[1, 2],
       [3, 4]])

In [82]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [83]:
# Swapaxes -> swap 2 specific axes in a matrix.

arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [84]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)

In [85]:
# Concatenation:

a = np.array([1,2])
b = np.array([3,4])

In [86]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [87]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [88]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [89]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [90]:
print(np.stack((arr1, arr2), axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [91]:
print(np.stack((arr1, arr2), axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [92]:
# Splitting Arrays:

arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

In [93]:
arr1


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [94]:
print(np.split(arr1, 4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [95]:
print(np.hsplit(arr1, 2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [96]:
#Repeating:

arr = np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [97]:
# tile -> repeat my whole array

print(np.tile(arr, 2))

[1 2 3 1 2 3]


In [98]:
#Aggregate Functions:

arr = np.array([1,2,3])
print(np.sum(arr))

6


In [99]:
np.mean(arr)

np.float64(2.0)

In [100]:
np.median(arr)

np.float64(2.0)

In [101]:
np.std(arr)

np.float64(0.816496580927726)

In [102]:
np.var(arr)

np.float64(0.6666666666666666)

In [103]:
np.max(arr)


np.int64(3)

In [104]:
np.min(arr)

np.int64(1)

In [105]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
print(np.sum(matrix, axis = 0))

[12 15 18]


In [107]:
# Cumulative Operations -> running total

arr

array([1, 2, 3])

In [108]:
print(np.cumsum(arr))

[1 3 6]


In [109]:
print(np.cumprod(arr))

[1 2 6]


In [110]:
#CONDITIONAL BASED CHOICES

# Where:

arr


array([1, 2, 3])

In [112]:
result = np.where(arr <2, "low", "high")

In [113]:
result


array(['low', 'high', 'high'], dtype='<U4')

In [114]:
arr

array([1, 2, 3])

In [115]:
#argwhere: row-column positions for 2d arrays

In [116]:
arr


array([1, 2, 3])

In [117]:
print(np.argwhere(arr>0))

[[0]
 [1]
 [2]]


In [118]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
print(np.argwhere(matrix> 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [120]:
# Logical and:

arr

array([1, 2, 3])

In [121]:
mask = np.logical_and(arr > 3, arr < 6)

In [122]:
arr[mask]

array([], dtype=int64)

In [123]:
# logical or:

mask = np.logical_or(arr < 4, arr > 5)
mask

array([ True,  True,  True])

In [124]:
arr[mask]

array([1, 2, 3])

In [125]:
arr2 = np.array([0, 1, 5, 0, 5])
arr2

array([0, 1, 5, 0, 5])

In [126]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [127]:
# Broadcasting

In [128]:
image = np.array([[200, 150], [100, 250]])
image.shape

(2, 2)

In [129]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [130]:
# Vectorization:

# np.vectorize() -> convert a regular function to be applied on an array.

In [131]:
def square(x):
  return x*x

vfunc = np.vectorize(square)

In [132]:
arr

array([1, 2, 3])

In [133]:
print(vfunc(arr))

[1 4 9]


In [134]:
# Dealing With Missing values:

# np.nan -> not a number.

In [135]:
a = np.array([1, 2, np.nan, 4])

In [136]:
a

array([ 1.,  2., nan,  4.])

In [137]:
# np.inf and -np.inf -> positive and negative infinites

In [138]:
# np.isnan
# np.isinf
# np.isfinite

# --> these are the functions used to detect any null values, infinte value or fnite value

In [139]:
print(np.isnan(a))

[False False  True False]


In [140]:
b = np.array([1, np.nan, np.inf, 10.2, 40])

In [141]:
print(np.isinf(b))

[False False  True False False]


In [142]:
new_b = np.nan_to_num(b) # remove Nan/ infinite values.

In [143]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])